INSERT INTO BLOCK_REASON (REASON) VALUES ('reason1');
INSERT INTO BLOCK_REASON (REASON) VALUES ('reason2');

INSERT INTO CANCELING_REASON (REASON) VALUES ('cancel reason2');
INSERT INTO CANCELING_REASON (REASON) VALUES ('cancel reason1');


INSERT INTO PROPERTY (AREA, HAS_AIR_CONDITION, HAS_BAR, HAS_DAILY_HOUSE_KEEPING, HAS_FITNESS_CENTER, HAS_FREE_WIFI, HAS_KITCHEN, HAS_OUTDOOR_SWIMMING_POOL, HAS_REST_ROOM, HAS_SAFE_BOX, ROOM_COUNT, PROPERTY_TYPE) VALUES (100, true, null, null, null, false, false, null, true, true, null, 'Commercial');
INSERT INTO PROPERTY (AREA, HAS_AIR_CONDITION, HAS_BAR, HAS_DAILY_HOUSE_KEEPING, HAS_FITNESS_CENTER, HAS_FREE_WIFI, HAS_KITCHEN, HAS_OUTDOOR_SWIMMING_POOL, HAS_REST_ROOM, HAS_SAFE_BOX, ROOM_COUNT, PROPERTY_TYPE) VALUES (50, true, true, true, false, true, true, false, null, true, 2, 'Hotel');
